version: '3'
services:
    proxy:
        image: nginx:1-alpine
        ports:
            - 8080:80
        volumes:
            - ./nginx-config.conf:/etc/nginx/nginx.conf:ro

    chimera:
        image: bptlab/chimera:dev
        ports:
            - 8081:8080
        environment:
            - CHIMERA_DEPLOY_NAME=Chimera
            - CHIMERA_DB_HOST=database
            - CHIMERA_DB_PORT=3306
            - CHIMERA_DB_USERNAME=root
            - CHIMERA_DB_PASSWORD=root
            - CHIMERA_DB_NAME=JEngineV2_ChimeraDev
            - UNICORN_URL=http://unicorn:8080
            - UNICORN_DEPLOY_NAME=/Unicorn
    unicorn:
        image: bptlab/unicorn:dev
        volumes:
            - ./server-config.xml:/usr/local/tomcat/conf/server-template.xml
        ports:
            - 8082:8080
        environment:
            - UNICORN_DEPLOY_NAME=Unicorn
            - UNICORN_DB_HOST=database
            - UNICORN_DB_PORT=3306
            - UNICORN_DB_USER=root
            - UNICORN_DB_PASSWORD=root
            - UNICORN_DB_DEV_DB=eap_development
            - UNICORN_DB_TEST_DB=eap_testing
    gryphon:
        image: bptlab/gryphon:dev
        volumes:
            - gryphon-mongodb-data:/var/lib/mongodb
    database:
        image: mysql:latest
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
volumes:
    gryphon-mongodb-data:
    mysql-data:
